// dev/web/client/src/views/McpView.tsx
import { useState, useEffect } from 'react'
import {
  fetchTools,
  createMCPServer,
  updateMCPServer,
  deleteMCPServer,
  testMCPConnection,
  type MCPServer,
  type MCPTestResult,
  type MCPConnectionStatus,
} from '@/api/tools'

export default function McpView() {
  const [servers, setServers] = useState<MCPServer[]>([])
  const [statuses, setStatuses] = useState<Record<string, MCPConnectionStatus>>({})
  const [loading, setLoading] = useState(true)

  const [showImport, setShowImport] = useState(false)
  const [importJson, setImportJson] = useState('')
  const [importError, setImportError] = useState('')

  const [editing, setEditing] = useState<{
    id?: string
    name: string
    command: string
    args: string
    env: string
    cwd: string
    timeout: number
  } | null>(null)

  const [testingMap, setTestingMap] = useState<Record<string, boolean>>({})
  const [testResults, setTestResults] = useState<Record<string, MCPTestResult>>({})

  async function load() {
    try {
      const data = await fetchTools()
      setServers(data.mcpServers)
      setStatuses(data.mcpStatuses || {})
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [])

  function statusOf(s: MCPServer): MCPConnectionStatus | null {
    return s.status ?? statuses[s.name] ?? null
  }

  function statusLabel(s: MCPServer): string {
    const st = statusOf(s)
    if (!st) return ''
    if (st.status === 'connected') return `已连接 (${st.toolsCount})`
    if (st.status === 'disabled') return '已禁用'
    if (st.status === 'failed') return `失败: ${st.error}`
    if (st.status === 'connecting') return '连接中...'
    return ''
  }

  async function handleTest(id: string) {
    setTestingMap(prev => ({ ...prev, [id]: true }))
    setTestResults(prev => { const n = { ...prev }; delete n[id]; return n })
    try {
      const result = await testMCPConnection(id)
      setTestResults(prev => ({ ...prev, [id]: result }))
    } finally {
      setTestingMap(prev => ({ ...prev, [id]: false }))
      load()
    }
  }

  function openNew() {
    setEditing({ name: '', command: '', args: '', env: '', cwd: '', timeout: 60 })
  }

  function openEdit(s: MCPServer) {
    setEditing({
      id: s.id,
      name: s.name,
      command: s.command,
      args: (s.args || []).join(' '),
      env: Object.entries(s.env || {}).map(([k, v]) => `${k}=${v}`).join('\n'),
      cwd: s.cwd || '',
      timeout: s.timeout || 60,
    })
  }

  async function handleSave() {
    if (!editing) return
    const args = editing.args ? editing.args.split(/\s+/).filter(Boolean) : []
    const env: Record<string, string> = {}
    for (const line of editing.env.split('\n')) {
      const eq = line.indexOf('=')
      if (eq > 0) env[line.slice(0, eq).trim()] = line.slice(eq + 1).trim()
    }
    const data: Record<string, unknown> = { name: editing.name, command: editing.command, args, env }
    if (editing.cwd) data.cwd = editing.cwd
    if (editing.timeout) data.timeout = editing.timeout
    if (editing.id) {
      await updateMCPServer(editing.id, data)
    } else {
      await createMCPServer(data)
    }
    setEditing(null)
    load()
  }

  async function handleDelete(id: string) {
    if (!confirm('确定删除此 MCP 服务器？')) return
    await deleteMCPServer(id)
    setServers(prev => prev.filter(s => s.id !== id))
  }

  async function handleImport() {
    setImportError('')
    try {
      const data = JSON.parse(importJson)
      if (!data.command) { setImportError('缺少 command 字段'); return }
      await createMCPServer({
        name: data.name || data.command,
        command: data.command,
        args: data.args || [],
        env: data.env || {},
        cwd: data.cwd,
        timeout: data.timeout,
      })
      setShowImport(false)
      setImportJson('')
      load()
    } catch {
      setImportError('无效的 JSON 格式')
    }
  }

  return (
    <div className="main">
      <div className="page-header">
        <span className="page-title">MCP 服务</span>
        <div className="header-actions">
          <button className="btn" onClick={() => setShowImport(true)}>导入 JSON</button>
          <button className="btn primary" onClick={openNew}>+ 添加服务</button>
        </div>
      </div>
      <div className="content">
        <div className="mcp-list">
          {loading ? (
            <div className="empty-state">加载中...</div>
          ) : servers.length === 0 ? (
            <div className="empty-state">
              <div className="empty-title">暂无 MCP 服务器</div>
              <div className="empty-hint">点击「添加服务」或「导入 JSON」来添加一个</div>
            </div>
          ) : (
            servers.map(s => {
              const st = statusOf(s)
              return (
                <div key={s.id} className="mcp-card">
                  <div className="mcp-header">
                    <span className="mcp-name">{s.name}</span>
                    {st && (
                      <span className={`mcp-status ${st.status}`}>{statusLabel(s)}</span>
                    )}
                    <button className="btn sm" disabled={testingMap[s.id]} onClick={() => handleTest(s.id)}>
                      {testingMap[s.id] ? '测试中...' : '测试'}
                    </button>
                    <button className="btn sm" onClick={() => openEdit(s)}>编辑</button>
                    <button className="btn sm danger" onClick={() => handleDelete(s.id)}>删除</button>
                  </div>
                  <div className="mcp-cmd">
                    {s.command} {s.args?.join(' ')}
                  </div>
                  {s.env && Object.keys(s.env).length > 0 && (
                    <div className="mcp-tools">
                      {Object.entries(s.env).map(([k, v]) => (
                        <span key={k} className="mcp-tool-tag">{k}={v}</span>
                      ))}
                    </div>
                  )}
                  {testResults[s.id] && (
                    <>
                      <div style={{
                        fontSize: 11,
                        padding: '4px 8px',
                        borderRadius: 4,
                        marginTop: 6,
                        background: testResults[s.id].ok ? 'rgba(42,157,92,0.08)' : 'rgba(196,92,60,0.08)',
                        color: testResults[s.id].ok ? 'var(--jade)' : 'var(--cinnabar)',
                      }}>
                        {testResults[s.id].ok
                          ? `连接成功（${testResults[s.id].toolCount} 个工具）`
                          : `测试失败: ${testResults[s.id].error}`}
                      </div>
                      {testResults[s.id].tools && testResults[s.id].tools!.length > 0 && (
                        <div className="mcp-tools">
                          {testResults[s.id].tools!.map(t => (
                            <span key={t.name} className="mcp-tool-tag" title={t.description}>{t.name}</span>
                          ))}
                        </div>
                      )}
                    </>
                  )}
                </div>
              )
            })
          )}
        </div>
      </div>

      {/* Import modal */}
      {showImport && (
        <div className="approval-overlay" onClick={() => setShowImport(false)}>
          <div className="approval-dialog" onClick={e => e.stopPropagation()} style={{ width: 480 }}>
            <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 12 }}>导入 MCP 配置</div>
            <p style={{ fontSize: 12, color: 'var(--ink-light)', margin: '-4px 0 12px' }}>
              粘贴 MCP 服务器 JSON 配置：
            </p>
            <textarea
              value={importJson}
              onChange={e => setImportJson(e.target.value)}
              placeholder={'{\n  "name": "Filesystem",\n  "command": "npx",\n  "args": ["-y", "server-package", "/tmp"],\n  "env": {"API_KEY": "xxx"}\n}'}
              rows={8}
              style={{
                width: '100%',
                padding: 8,
                border: '1px solid var(--border)',
                borderRadius: 6,
                fontSize: 13,
                fontFamily: 'inherit',
                background: 'var(--bg-input)',
                color: 'var(--ink-deep)',
                resize: 'vertical',
                boxSizing: 'border-box',
              }}
            />
            {importError && (
              <p style={{ fontSize: 12, color: 'var(--cinnabar)', margin: '6px 0 0' }}>{importError}</p>
            )}
            <div style={{ display: 'flex', gap: 8, marginTop: 16, justifyContent: 'flex-end' }}>
              <button className="btn" onClick={() => setShowImport(false)}>取消</button>
              <button className="btn primary" onClick={handleImport}>导入</button>
            </div>
          </div>
        </div>
      )}

      {/* Edit / New modal */}
      {editing && (
        <div className="approval-overlay" onClick={() => setEditing(null)}>
          <div className="approval-dialog" onClick={e => e.stopPropagation()} style={{ width: 480 }}>
            <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 16 }}>
              {editing.id ? '编辑 MCP 服务器' : '新建 MCP 服务器'}
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div>
                <label style={labelStyle}>名称</label>
                <input
                  value={editing.name}
                  onChange={e => setEditing({ ...editing, name: e.target.value })}
                  placeholder="例如：Filesystem"
                  style={inputStyle}
                />
              </div>
              <div>
                <label style={labelStyle}>命令</label>
                <input
                  value={editing.command}
                  onChange={e => setEditing({ ...editing, command: e.target.value })}
                  placeholder="例如：npx"
                  style={inputStyle}
                />
              </div>
              <div>
                <label style={labelStyle}>参数</label>
                <input
                  value={editing.args}
                  onChange={e => setEditing({ ...editing, args: e.target.value })}
                  placeholder="例如：-y @modelcontextprotocol/server-filesystem /tmp"
                  style={inputStyle}
                />
              </div>
              <div>
                <label style={labelStyle}>环境变量（每行一个 KEY=VALUE）</label>
                <textarea
                  value={editing.env}
                  onChange={e => setEditing({ ...editing, env: e.target.value })}
                  placeholder="API_KEY=xxx\nBASE_URL=http://..."
                  rows={3}
                  style={{ ...inputStyle, resize: 'vertical' }}
                />
              </div>
              <div style={{ display: 'flex', gap: 12 }}>
                <div style={{ flex: 1 }}>
                  <label style={labelStyle}>工作目录 (cwd)</label>
                  <input
                    value={editing.cwd}
                    onChange={e => setEditing({ ...editing, cwd: e.target.value })}
                    placeholder="可选，留空用项目根目录"
                    style={inputStyle}
                  />
                </div>
                <div style={{ flex: 1 }}>
                  <label style={labelStyle}>超时 (秒)</label>
                  <input
                    type="number"
                    value={editing.timeout}
                    onChange={e => setEditing({ ...editing, timeout: Number(e.target.value) })}
                    placeholder="默认 60"
                    style={inputStyle}
                  />
                </div>
              </div>
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 20, justifyContent: 'flex-end' }}>
              <button className="btn" onClick={() => setEditing(null)}>取消</button>
              <button className="btn primary" onClick={handleSave}>保存</button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

const labelStyle: React.CSSProperties = {
  display: 'block',
  fontSize: 12,
  color: 'var(--ink-light)',
  marginBottom: 4,
}

const inputStyle: React.CSSProperties = {
  width: '100%',
  padding: '8px 10px',
  border: '1px solid var(--border)',
  borderRadius: 6,
  fontSize: 13,
  fontFamily: 'inherit',
  background: 'var(--bg-input)',
  color: 'var(--ink-deep)',
  outline: 'none',
  boxSizing: 'border-box',
}

// dev/web/client-old/src/views/McpView.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToolsStore } from '@/stores/tools'
import type { MCPServer } from '@/api/tools'

const { t } = useI18n()
const store = useToolsStore()

const showImportModal = ref(false)
const importJson = ref('')
const importError = ref('')

const editingMCP = ref<{
  id?: string
  name: string
  command: string
  args: string
  env: string
  cwd: string
  timeout: number
} | null>(null)

const testingMap = ref<Record<string, boolean>>({})
const testResults = ref<Record<string, { ok: boolean; error?: string; toolCount?: number }>>({})

function statusLabel(s: MCPServer): string {
  const st = s.status || store.mcpStatuses[s.name]
  if (!st) return ''
  if (st.status === 'connected') return `${t('toolSetting.statusConnected')} (${st.toolsCount})`
  if (st.status === 'disabled') return t('toolSetting.statusDisabled')
  if (st.status === 'failed') return `${t('toolSetting.statusFailed')}: ${st.error}`
  if (st.status === 'connecting') return t('toolSetting.statusConnecting')
  return ''
}

function statusClass(s: MCPServer): string {
  const st = s.status || store.mcpStatuses[s.name]
  if (!st) return ''
  if (st.status === 'connected') return 'mcp-status--connected'
  if (st.status === 'failed') return 'mcp-status--failed'
  if (st.status === 'disabled') return 'mcp-status--disabled'
  if (st.status === 'connecting') return 'mcp-status--connecting'
  return ''
}

async function testConnection(id: string) {
  testingMap.value = { ...testingMap.value, [id]: true }
  delete testResults.value[id]
  try {
    const result = await store.testMCP(id)
    testResults.value = { ...testResults.value, [id]: result }
  } finally {
    testingMap.value = { ...testingMap.value, [id]: false }
    store.load()
  }
}

function newMCP() {
  editingMCP.value = { name: '', command: '', args: '', env: '', cwd: '', timeout: 60 }
}

function editMCP(s: MCPServer) {
  editingMCP.value = {
    id: s.id,
    name: s.name,
    command: s.command,
    args: (s.args || []).join(' '),
    env: Object.entries(s.env || {}).map(([k, v]) => `${k}=${v}`).join('\n'),
    cwd: s.cwd || '',
    timeout: s.timeout || 60,
  }
}

function cancelEdit() {
  editingMCP.value = null
}

async function saveMCP() {
  if (!editingMCP.value) return
  const e = editingMCP.value
  const args = e.args ? e.args.split(/\s+/).filter(Boolean) : []
  const env: Record<string, string> = {}
  for (const line of e.env.split('\n')) {
    const eq = line.indexOf('=')
    if (eq > 0) env[line.slice(0, eq).trim()] = line.slice(eq + 1).trim()
  }
  const data: Record<string, any> = { name: e.name, command: e.command, args, env }
  if (e.cwd) data.cwd = e.cwd
  if (e.timeout) data.timeout = e.timeout
  if (e.id) {
    await store.updateMCP(e.id, data)
  } else {
    await store.createMCP(data)
  }
  editingMCP.value = null
  store.load()
}

async function removeMCP(id: string) {
  if (confirm(t('toolSetting.deleteConfirm'))) await store.removeMCP(id)
}

function openImport() {
  importJson.value = ''
  importError.value = ''
  showImportModal.value = true
}

async function doImport() {
  importError.value = ''
  try {
    const data = JSON.parse(importJson.value)
    if (!data.command) { importError.value = t('toolSetting.importMissingCommand'); return }
    await store.createMCP({
      name: data.name || data.command,
      command: data.command,
      args: data.args || [],
      env: data.env || {},
      cwd: data.cwd,
      timeout: data.timeout,
    })
    showImportModal.value = false
    store.load()
  } catch {
    importError.value = t('toolSetting.importInvalidJson')
  }
}

onMounted(() => { store.load() })
</script>

<template>
  <div class="mcp-page">
    <div class="mcp-header">
      <h3 class="mcp-title">MCP {{ t('toolSetting.mcpSection') }}</h3>
      <div class="mcp-header-actions">
        <button class="btn-import" @click="openImport">{{ t('toolSetting.importBtn') }}</button>
        <button class="btn-add-mcp" @click="newMCP">{{ t('toolSetting.addMCP') }}</button>
      </div>
    </div>

    <div v-if="store.mcpServers.length === 0" class="mcp-empty">
      {{ t('toolSetting.noMCP') }}
    </div>

    <div v-for="s in store.mcpServers" :key="s.id" class="mcp-card">
      <div class="mcp-card-header">
        <div class="mcp-card-info">
          <span class="mcp-name">{{ s.name }}</span>
          <span class="mcp-command">{{ s.command }} {{ s.args?.join(' ') }}</span>
        </div>
        <span v-if="statusLabel(s)" :class="['mcp-status-badge', statusClass(s)]">{{ statusLabel(s) }}</span>
      </div>
      <div v-if="s.env && Object.keys(s.env).length > 0" class="mcp-env">
        <span v-for="(v, k) in s.env" :key="k" class="mcp-env-item">{{ k }}={{ v }}</span>
      </div>
      <div v-if="testResults[s.id]" :class="['mcp-test-result', testResults[s.id].ok ? 'mcp-test-ok' : 'mcp-test-fail']">
        {{ testResults[s.id].ok ? t('toolSetting.testSuccess', { count: testResults[s.id].toolCount }) : t('toolSetting.testFailed') + ': ' + testResults[s.id].error }}
      </div>
      <div class="mcp-actions">
        <button class="btn-sm" :disabled="testingMap[s.id]" @click="testConnection(s.id)">
          {{ testingMap[s.id] ? t('toolSetting.testing') : t('toolSetting.test') }}
        </button>
        <button class="btn-sm" @click="editMCP(s)">{{ t('toolSetting.edit') }}</button>
        <button class="btn-sm btn-sm-danger" @click="removeMCP(s.id)">{{ t('toolSetting.delete') }}</button>
      </div>
    </div>

    <div v-if="showImportModal" class="edit-form-overlay" @click.self="showImportModal = false">
      <div class="edit-form">
        <h4 class="form-title">{{ t('toolSetting.importTitle') }}</h4>
        <p class="form-desc">{{ t('toolSetting.importDesc') }}</p>
        <div class="form-group">
          <textarea v-model="importJson" :placeholder="t('toolSetting.importPlaceholder')" rows="8" />
        </div>
        <p v-if="importError" class="import-error">{{ importError }}</p>
        <div class="form-actions">
          <button class="btn-primary" @click="doImport">{{ t('toolSetting.importConfirm') }}</button>
          <button class="btn-cancel" @click="showImportModal = false">{{ t('toolSetting.cancel') }}</button>
        </div>
      </div>
    </div>

    <div v-if="editingMCP" class="edit-form-overlay" @click.self="cancelEdit">
      <div class="edit-form">
        <h4 class="form-title">{{ editingMCP.id ? t('toolSetting.editMCPSection') : t('toolSetting.newMCPSection') }}</h4>
        <div class="form-group">
          <label>{{ t('toolSetting.nameLabel') }}</label>
          <input v-model="editingMCP.name" :placeholder="t('toolSetting.namePlaceholder')" />
        </div>
        <div class="form-group">
          <label>{{ t('toolSetting.commandLabel') }}</label>
          <input v-model="editingMCP.command" :placeholder="t('toolSetting.commandPlaceholder')" />
        </div>
        <div class="form-group">
          <label>{{ t('toolSetting.argsLabel') }}</label>
          <input v-model="editingMCP.args" :placeholder="t('toolSetting.argsPlaceholder')" />
        </div>
        <div class="form-group">
          <label>{{ t('toolSetting.envLabel') }}</label>
          <textarea v-model="editingMCP.env" :placeholder="t('toolSetting.envPlaceholder')" rows="3" />
        </div>
        <div class="form-row">
          <div class="form-group form-group-half">
            <label>工作目录 (cwd)</label>
            <input v-model="editingMCP.cwd" placeholder="可选，留空用项目根目录" />
          </div>
          <div class="form-group form-group-half">
            <label>超时 (秒)</label>
            <input v-model.number="editingMCP.timeout" type="number" placeholder="默认 60" />
          </div>
        </div>
        <div class="form-actions">
          <button class="btn-primary" @click="saveMCP">{{ t('toolSetting.save') }}</button>
          <button class="btn-cancel" @click="cancelEdit">{{ t('toolSetting.cancel') }}</button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.mcp-page {
  flex: 1;
  padding: 24px 32px;
  overflow-y: auto;
  background: #fff;
}

.mcp-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
  flex-wrap: wrap;
  gap: 8px;
}

.mcp-title {
  font-size: 18px;
  font-weight: 600;
  margin: 0;
}

.mcp-header-actions { display: flex; gap: 8px; }
.btn-import { padding: 5px 14px; border: 1px solid #1976d2; border-radius: 4px; font-size: 12px; background: #fff; color: #1976d2; cursor: pointer; transition: all 0.15s; }
.btn-import:hover { background: #e3f2fd; }
.btn-add-mcp { padding: 5px 14px; border: none; border-radius: 4px; font-size: 12px; background: #1976d2; color: #fff; cursor: pointer; }
.btn-add-mcp:hover { background: #1565c0; }

.mcp-empty { text-align: center; padding: 24px; font-size: 13px; color: #999; border: 1px dashed #ddd; border-radius: 8px; }
.mcp-card { border: 1px solid #e0e0e0; border-radius: 8px; padding: 14px; margin-bottom: 10px; background: #fafafa; }
.mcp-card-info { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
.mcp-name { font-size: 14px; font-weight: 600; color: #333; }
.mcp-command { font-size: 12px; color: #888; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.mcp-status-badge { font-size: 10px; padding: 2px 8px; border-radius: 10px; font-weight: 500; white-space: nowrap; flex-shrink: 0; }
.mcp-status--connected { background: #e8f5e9; color: #2e7d32; }
.mcp-status--failed { background: #fce4ec; color: #c62828; }
.mcp-status--disabled { background: #f5f5f5; color: #9e9e9e; }
.mcp-status--connecting { background: #fff8e1; color: #f57f17; }
.mcp-test-result { font-size: 11px; padding: 4px 8px; border-radius: 4px; margin-top: 6px; }
.mcp-test-ok { background: #e8f5e9; color: #2e7d32; }
.mcp-test-fail { background: #fce4ec; color: #c62828; }
.mcp-env { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 8px; }
.mcp-env-item { font-size: 11px; padding: 2px 6px; border-radius: 4px; background: #e3f2fd; color: #1976d2; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.mcp-actions { display: flex; gap: 6px; margin-top: 10px; padding-top: 10px; border-top: 1px solid #eee; }
.btn-sm { padding: 4px 12px; border: 1px solid #ddd; border-radius: 4px; font-size: 12px; background: #fff; cursor: pointer; color: #333; }
.btn-sm:hover { background: #e3f2fd; border-color: #90caf9; }
.btn-sm-danger:hover { background: #fce4ec; border-color: #ef9a9a; color: #d32f2f; }

.form-desc { font-size: 12px; color: #888; margin: -8px 0 12px; }
.import-error { font-size: 12px; color: #d32f2f; margin: 0 0 8px; }

.edit-form-overlay {
  position: fixed; inset: 0; background: rgba(0,0,0,0.3);
  display: flex; align-items: center; justify-content: center; z-index: 200;
}
.edit-form {
  background: #fff; border-radius: 12px; padding: 24px; width: 480px;
  max-height: 80vh; overflow-y: auto; box-shadow: 0 8px 32px rgba(0,0,0,0.15);
}
.form-title { font-size: 16px; font-weight: 600; margin-bottom: 16px; }
.form-group { margin-bottom: 12px; }
.form-group label { display: block; font-size: 12px; color: #666; margin-bottom: 4px; font-weight: 500; }
.form-group input, .form-group textarea { width: 100%; padding: 8px 10px; border: 1px solid #ddd; border-radius: 4px; font-size: 13px; outline: none; font-family: inherit; box-sizing: border-box; }
.form-group input:focus, .form-group textarea:focus { border-color: #1976d2; }
.form-group textarea { resize: vertical; }
.form-row { display: flex; gap: 12px; }
.form-group-half { flex: 1; }
.form-actions { display: flex; gap: 8px; margin-top: 16px; }
.btn-primary { padding: 7px 16px; background: #1976d2; color: #fff; border: none; border-radius: 4px; font-size: 13px; cursor: pointer; }
.btn-primary:hover { background: #1565c0; }
.btn-cancel { padding: 7px 16px; background: #fff; color: #666; border: 1px solid #ddd; border-radius: 4px; font-size: 13px; cursor: pointer; }
.btn-cancel:hover { background: #f5f5f5; }
</style>
