// dev/web/client/src/views/ChatView.tsx
import { useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { useChatStore } from '@/stores/chatStore'
import ChatArea from '@/components/Chat/ChatArea'
import SidePanel from '@/components/Panels/SidePanel'

export default function ChatView() {
  const { id } = useParams<{ id: string }>()
  const { switchSession, loadSessions, sessions } = useChatStore()

  useEffect(() => {
    if (sessions.length === 0) {
      loadSessions()
    }
  }, [])

  useEffect(() => {
    if (id) {
      switchSession(id)
    }
  }, [id])

  return (
    <div className="chat-view">
      <ChatArea />
      <SidePanel />
    </div>
  )
}

// dev/web/client/src/views/ChatView.vue
<script setup lang="ts">
import { watch, computed } from 'vue'
import { useRoute } from 'vue-router'
import { useChatStore } from '@/stores/chat'
import ChatArea from '@/components/ChatArea.vue'
import SidePanel from '@/components/Panels/SidePanel.vue'

const route = useRoute()
const chatStore = useChatStore()

watch(() => route.params.id, (id) => {
  if (id && typeof id === 'string') {
    chatStore.switchSession(id)
  }
}, { immediate: true })

const showSidePanel = computed(() => route.name === 'chat-files' || route.name === 'chat-outline')
</script>

<template>
  <div class="chat-view">
    <ChatArea />
    <SidePanel v-if="showSidePanel" />
  </div>
</template>

<style scoped>
.chat-view { flex: 1; display: flex; min-width: 0; }
</style>
